apiVersion: ray.io/v1
kind: RayService
metadata:
  name: gemma-3-4b
spec:
  serveConfigV2: |
    applications:
    - name: llm
      route_prefix: /
      import_path:  ray-operator.config.samples.vllm.serve:model
      deployments:
      - name: VLLMDeployment
        num_replicas: 1
        ray_actor_options:
          num_cpus: 2
      runtime_env:
        working_dir: "https://github.com/ray-project/kuberay/archive/master.zip"
        pip: ["vllm==0.6.1.post2", "huggingface_hub>=0.29.0", "transformers>=4.36.0"]
        env_vars:
          MODEL_ID: "google/gemma-3-4b-it"
          TENSOR_PARALLELISM: "2"
          PIPELINE_PARALLELISM: "1"
          TRANSFORMERS_CACHE: "/tmp/transformers_cache"
          HF_HOME: "/tmp/hf_home"
          HF_HUB_ENABLE_HF_TRANSFER: "1"
  rayClusterConfig:
    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"
      template:
        spec:
          containers:
            - name: ray-head
              image: rayproject/ray-ml:2.33.0.914af0-py311
              resources:
                limits:
                  cpu: "2"
                  memory: "8Gi"
                requests:
                  cpu: "2"
                  memory: "8Gi"
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
              env:
                - name: HUGGING_FACE_HUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: hf-secret
                      key: hf_api_token
    workerGroupSpecs:
      - replicas: 1
        minReplicas: 0
        maxReplicas: 4
        groupName: gpu-group
        rayStartParams: {}
        template:
          spec:
            containers:
              - name: llm
                image: rayproject/ray-ml:2.33.0.914af0-py311
                env:
                  - name: HUGGING_FACE_HUB_TOKEN
                    valueFrom:
                      secretKeyRef:
                        name: hf-secret
                        key: hf_api_token
                resources:
                  limits:
                    cpu: "8"
                    memory: "20Gi"
                    nvidia.com/gpu: "2"
                  requests:
                    cpu: "8"
                    memory: "20Gi"
                    nvidia.com/gpu: "2"
            tolerations:
              - key: "nvidia.com/gpu"
                operator: "Exists"
                effect: "NoSchedule"
