apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gemma-2b
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
  volumeMode: Filesystem
---
apiVersion: v1
kind: Secret
metadata:
  name: hf-token-secret
  namespace: default
type: Opaque
data:
  token: "aGZfblRPcExLQWx2Y2FXekdVYWVzZU5KQlZRY0ZERVJWdEpvQQ=="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemma-2b
  namespace: default
  labels:
    app: gemma-2b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemma-2b
  template:
    metadata:
      labels:
        app: gemma-2b
    spec:
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: gemma-2b
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "1Gi"
      containers:
        - name: gemma-2b
          image: vllm/vllm-openai:v0.8.3
          command: ["/bin/sh", "-c"]
          args:
            [
              "vllm serve google/gemma-1.1-2b-it --trust-remote-code --enable-chunked-prefill --max-num-seqs 64",
            ]
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token-secret
                  key: token
            - name: PYTHONUNBUFFERED
              value: "1"
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "6"
              memory: "8Gi"
              nvidia.com/gpu: "1"
            requests:
              cpu: "2"
              memory: "8Gi"
              nvidia.com/gpu: "1"
          volumeMounts:
            - mountPath: /root/.cache/huggingface
              name: cache-volume
            - name: shm
              mountPath: /dev/shm
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 180
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 180
            periodSeconds: 5
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
        cloud.google.com/gke-gpu-driver-version: latest

---
apiVersion: v1
kind: Service
metadata:
  name: gemma-2b
  namespace: default
spec:
  ports:
    - name: http-gemma-2b
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: gemma-2b
  sessionAffinity: None
  type: ClusterIP
