apiVersion: apps/v1
kind: Deployment
metadata:
  name: MODEL_NAME_PLACEHOLDER
  namespace: default
  labels:
    app: MODEL_NAME_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MODEL_NAME_PLACEHOLDER
  template:
    metadata:
      labels:
        app: MODEL_NAME_PLACEHOLDER
        component: vllm
    spec:
      volumes:
        - name: cache-volume
          emptyDir:
            sizeLimit: "50Gi"
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "2Gi"
      containers:
        - name: vllm-model
          image: vllm/vllm-openai:v0.8.3
          command: ["/bin/sh", "-c"]
          args:
            [
              "vllm serve HF_MODEL_PATH --trust-remote-code --enable-chunked-prefill=false --max-num-seqs MAX_SEQ_PLACEHOLDER",
            ]
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token-secret
                  key: token
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: VLLM_WORKER_MAX_BATCH_SIZE
              value: "BATCH_SIZE_PLACEHOLDER"
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "8"
              memory: "20Gi"
              nvidia.com/gpu: "1"
            requests:
              cpu: "4"
              memory: "20Gi"
              nvidia.com/gpu: "1"
          volumeMounts:
            - mountPath: /root/.cache/huggingface
              name: cache-volume
            - name: shm
              mountPath: /dev/shm
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 300
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 300
            periodSeconds: 30
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
---
apiVersion: v1
kind: Service
metadata:
  name: MODEL_NAME_PLACEHOLDER
  namespace: default
spec:
  ports:
    - name: http-vllm
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: MODEL_NAME_PLACEHOLDER
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: MODEL_NAME_PLACEHOLDER-monitoring
  namespace: default
  labels:
    app.kubernetes.io/name: vllm
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  endpoints:
    - port: 8000
      scheme: http
      interval: 10s
      path: /metrics
  selector:
    matchLabels:
      app: MODEL_NAME_PLACEHOLDER
