apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: vllm
  namespace: default
  labels:
    app.kubernetes.io/name: vllm
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  endpoints:
    - port: 8000
      scheme: http
      interval: 10s
      path: /metrics
  selector:
    matchLabels:
      app: gemma-2b
